# Changes here will be overwritten by Copier
_commit: 0.6.1
_src_path: https://github.com/nlesc/python-template.git
copyright_holder: Louise Grimble
email: louiseegrimble@gmail.com
full_name: Louise Grimble
github_organization: louisegrimble
keywords: dessert,sweet
license: Apachev2
package_name: baklava
package_short_description: A sweet package
template_profile: minimum
version: 0.1.0
